[package]
name = "resoom"
version = "0.1.0"
authors = ["adrianisuru <adrianisuru@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
which = "3.1.1"
log = "0.4.8"
clap = "2.33.1"
